services:
  linuxgsm-css:
    image: gameservermanagers/gameserver:css
    # image: ghcr.io/gameservermanagers/gameserver:csgo
    container_name: css-server
    volumes:
      - ./css-data:/data
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"
    restart: unless-stopped