version: "3.8"
services:
  linuxgsm-css:
    image: gameservermanagers/gameserver:css
    container_name: css-server
    volumes:
      - ./css-data:/data # Server data
      - ./init.sh:/init.sh # Init the server with our plugins
      - ./mods:/mods # PLugins zip files
      - ./maps:/data/serverfiles/cstrike/maps # Maps .bsp files + SQL files for mapzones/maptiers
      - ./startparams.cfg:/data/config-lgsm/cssserver/cssserver.cfg # Server config (needed to inject -tickrate 100)
      - ./cssserver.cfg:/data/serverfiles/cstrike/cfg/cssserver.cfg # Server config (contains server name, rcon password, etc.)
      - ./sql/shavit.sq3:/data/serverfiles/cstrike/addons/sourcemod/data/sqlite/shavit.sq3 # Premade database with all zones & tiers
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      - CONTAINER_NAME=css-server

  # monitor:
  #   build: ./monitor
  #   container_name: css-monitor
  #   restart: unless-stopped
  #   depends_on:
  #     - linuxgsm-css
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
  #     - CONTAINER_NAME=css-server
  #     - CHECK_INTERVAL=10000
  #     - DOCKER_SOCKET=/var/run/docker.sock
