version: "3.8"
services:
  linuxgsm-css:
    image: gameservermanagers/gameserver:css
    container_name: css-server
    volumes:
      - ./css-data:/data
      - ./init.sh:/init.sh
      - ./mods/bhoptimer.zip:/mods/bhoptimer.zip
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
    restart: unless-stopped
